---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ghrcehosting/public_html
    - export REPOPATH=/home/ghrcehosting/repositories/ACM # Adjust to your repo path
    - cd $REPOPATH
    - npm install
    - npm run build
    - /bin/cp -R dist/* $DEPLOYPATH
